name: authify
description: "A modular Firebase Authentication system built with Flutter and GetX."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.1.2

  # Firebase Core Services
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter

  # State Management & Routing
  get: ^4.6.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png

  android_12:
    color: "#ffffff"
    image: assets/logo.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
