// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpgCmSKLGlWzM-GqJJTQxjAu3AukrvzKE',
    appId: '1:471132261733:web:bb59af5d2b7944118ae58c',
    messagingSenderId: '471132261733',
    projectId: 'authify-8494a',
    authDomain: 'authify-8494a.firebaseapp.com',
    storageBucket: 'authify-8494a.firebasestorage.app',
    measurementId: 'G-22PEWHJH9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiInmyT5yZE1JUmgjVFD7Z18xHQolnoEc',
    appId: '1:471132261733:android:bcafc9177e1d6c348ae58c',
    messagingSenderId: '471132261733',
    projectId: 'authify-8494a',
    storageBucket: 'authify-8494a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiy0-GMCkntibBbZQPPp0isD_UbibYsEQ',
    appId: '1:471132261733:ios:efa800089b8313168ae58c',
    messagingSenderId: '471132261733',
    projectId: 'authify-8494a',
    storageBucket: 'authify-8494a.firebasestorage.app',
    iosBundleId: 'com.example.authify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiy0-GMCkntibBbZQPPp0isD_UbibYsEQ',
    appId: '1:471132261733:ios:efa800089b8313168ae58c',
    messagingSenderId: '471132261733',
    projectId: 'authify-8494a',
    storageBucket: 'authify-8494a.firebasestorage.app',
    iosBundleId: 'com.example.authify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpgCmSKLGlWzM-GqJJTQxjAu3AukrvzKE',
    appId: '1:471132261733:web:d54fc36da1fd00808ae58c',
    messagingSenderId: '471132261733',
    projectId: 'authify-8494a',
    authDomain: 'authify-8494a.firebaseapp.com',
    storageBucket: 'authify-8494a.firebasestorage.app',
    measurementId: 'G-DC80ZRZCZC',
  );
}
